name: _fluttorch_workspace
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - examples/typed_api
  - examples/voltacast
  - packages/fluttorch
  - packages/fluttorch_executorch
  - packages/fluttorch_gen
  - packages/fluttorch_litert
  - packages/fluttorch_onnx
  - packages/fluttorch_test

dev_dependencies:
  lints: ^6.0.0
