import 'package:dart_style/dart_style.dart';
import 'package:fluttorch/fluttorch.dart';
import 'package:pub_semver/pub_semver.dart';

import 'generator.dart';
import 'names.dart';

/// Formats generated source the way the rest of the repository is formatted.
///
/// Doing it here rather than leaving it to a later `dart format` pass means the
/// emitter's output is the final text: a pinned golden cannot then differ from
/// what the emitter produces over nothing but line breaks.
final _formatter = DartFormatter(languageVersion: Version(3, 9, 0));

/// Turns a manifest into Dart source.
///
/// A pure function of the manifest, deliberately: `build_runner` is a thin
/// wrapper over it, so the generator can be tested — and its output pinned —
/// without a build.
///
/// Everything the generated code knows comes from the manifest. Nothing is
/// inferred, and nothing the manifest does not describe is emitted; a generator
/// that guessed would be a second source of truth, which is the failure this
/// whole project exists to prevent.
String emit(ModelManifest manifest, {required String sourceName}) {
  checkGeneratable(manifest);
  checkDistinct(manifest.inputs.map((s) => s.name), 'inputs');
  checkDistinct(manifest.outputs.map((s) => s.name), 'outputs');

  final model = pascalCase(manifest.name);
  final b = StringBuffer();

  b
    ..writeln('// GENERATED BY fluttorch_gen — do not edit.')
    ..writeln('//')
    ..writeln('// Source: $sourceName')
    ..writeln('// Manifest schema ${manifest.schemaVersion}')
    ..writeln('// Weights: ${manifest.weightHash}')
    ..writeln('//')
    ..writeln(
      '// Editing this file lets the Dart side disagree with the export it',
    )
    ..writeln(
      '// came from, which is the failure this generator exists to prevent.',
    )
    ..writeln('// Change the model, re-export, and rebuild.')
    ..writeln()
    ..writeln('// ignore_for_file: unnecessary_cast, unused_import')
    ..writeln()
    ..writeln("import 'dart:typed_data';")
    ..writeln()
    ..writeln("import 'package:fluttorch/fluttorch.dart';")
    ..writeln();

  for (final spec in manifest.inputs) {
    _tensorType(b, model, spec, manifest, isInput: true);
  }
  for (final spec in manifest.outputs) {
    _tensorType(b, model, spec, manifest, isInput: false);
  }

  _outputsClass(b, model, manifest);
  _modelClass(b, model, manifest, sourceName);

  return _formatter.format(b.toString());
}

// ── one type per tensor ────────────────────────────────────────────────────────

String _typeName(String model, TensorSpec spec) =>
    '$model${pascalCase(spec.name)}';

void _tensorType(
  StringBuffer b,
  String model,
  TensorSpec spec,
  ModelManifest manifest, {
  required bool isInput,
}) {
  final type = _typeName(model, spec);
  final listType = _listType(spec.dtype);
  final role = isInput ? 'input' : 'output';

  b
    ..writeln(
      '/// The `${spec.name}` $role: '
      '`${spec.dtype.wireName}${spec.shape}`.',
    )
    ..writeln('///')
    ..writeln(
      '/// A distinct type rather than a bare [Tensor], so passing the wrong',
    )
    ..writeln(
      '/// tensor to [$model.run] is a compile error rather than a shape',
    )
    ..writeln(
      '/// mismatch discovered at inference. The wrapper costs nothing at',
    )
    ..writeln('/// run time.')
    ..writeln('extension type const $type._(Tensor tensor) {');

  b
    ..writeln('  /// What the export declared for this tensor.')
    ..writeln('  static const TensorSpec spec = TensorSpec(')
    ..writeln("    name: '${spec.name}',")
    ..writeln('    dtype: DType.${spec.dtype.name},')
    ..writeln('    shape: [${spec.shape.join(', ')}],')
    ..writeln('  );')
    ..writeln();

  if (!spec.isDynamic && listType != null) {
    b
      ..writeln(
        '  /// Wraps ${spec.elementCount} `${spec.dtype.wireName}` values.',
      )
      ..writeln('  ///')
      ..writeln(
        '  /// Throws [TensorShapeException] unless [values] holds exactly',
      )
      ..writeln(
        '  /// ${spec.elementCount}; the shape itself is fixed by the export.',
      )
      ..writeln('  factory $type($listType values) {')
      ..writeln('    if (values.length != ${spec.elementCount}) {')
      ..writeln('      throw TensorShapeException(')
      ..writeln(
        "        'expected ${spec.elementCount} values, got \${values.length}',",
      )
      ..writeln("        tensorName: '${spec.name}',")
      ..writeln('      );')
      ..writeln('    }')
      ..writeln('    return $type._(')
      ..writeln(
        '      Tensor.view(spec: spec, bytes: values.buffer.asUint8List(',
      )
      ..writeln('        values.offsetInBytes,')
      ..writeln('        values.lengthInBytes,')
      ..writeln('      )),')
      ..writeln('    );')
      ..writeln('  }')
      ..writeln()
      ..writeln('  /// An all-zero tensor, for use as a destination buffer.')
      ..writeln('  factory $type.zeros() => $type._(Tensor.zeros(spec));')
      ..writeln();
  }

  if (spec.isDynamic) {
    b
      ..writeln('  /// The escape hatch for this tensor\'s dynamic dimensions.')
      ..writeln('  ///')
      ..writeln(
        '  /// `${spec.shape}` is not fully known at build time, so the shape',
      )
      ..writeln(
        '  /// cannot be checked by the compiler and is checked here instead.',
      )
      ..writeln(
        '  /// This is the only constructor for a dynamic tensor, and it is',
      )
      ..writeln('  /// deliberately the wordy one.')
      ..writeln('  factory $type.withShape({')
      ..writeln('    required Uint8List bytes,')
      ..writeln('    required List<int> shape,')
      ..writeln(
        '  }) => $type._(Tensor.view(spec: spec, bytes: bytes, shape: shape));',
      )
      ..writeln();
  }

  b
    ..writeln('  /// Wraps a tensor that already satisfies [spec].')
    ..writeln('  ///')
    ..writeln(
      '  /// Throws [TensorShapeException] or [DTypeMismatchException] if it',
    )
    ..writeln('  /// does not.')
    ..writeln('  factory $type.wrap(Tensor tensor) {')
    ..writeln(
      '    checkTensorsAgainst([spec], [tensor], role: \'${spec.name}\');',
    )
    ..writeln('    return $type._(tensor);')
    ..writeln('  }')
    ..writeln();

  if (listType != null) {
    b
      ..writeln('  /// The values, over the same memory. No copy is made.')
      ..writeln('  $listType get values => tensor.${_viewCall(spec.dtype)};')
      ..writeln();
  } else {
    b
      ..writeln(
        '  /// Raw bytes. `${spec.dtype.wireName}` has no Dart list view, so',
      )
      ..writeln('  /// this is the only representation available.')
      ..writeln('  Uint8List get bytes => tensor.bytes;')
      ..writeln();
  }

  b
    ..writeln(
      '  /// The concrete shape, which for a dynamic spec is known only here.',
    )
    ..writeln('  List<int> get shape => tensor.shape;')
    ..writeln('}')
    ..writeln();

  if (isInput) _preprocessing(b, type, spec, manifest);
}

// ── preprocessing, generated from the manifest ─────────────────────────────────

void _preprocessing(
  StringBuffer b,
  String type,
  TensorSpec spec,
  ModelManifest manifest,
) {
  if (manifest.preprocessing.isEmpty) return;
  if (spec.dtype != DType.float32) return;

  b
    ..writeln('/// The transforms the export recorded for `${spec.name}`.')
    ..writeln('///')
    ..writeln(
      '/// Generated from the manifest, so they cannot drift from the ones',
    )
    ..writeln(
      '/// training applied — which is the whole reason they are not written',
    )
    ..writeln('/// by hand.')
    ..writeln('extension ${type}Preprocessing on $type {')
    ..writeln('  /// Applies every recorded step, in order, in place.')
    ..writeln('  ///')
    ..writeln(
      '  /// In place because the caller owns the buffer and a preprocessing',
    )
    ..writeln('  /// pass that allocated would undo the point of owning it.')
    ..writeln('  void preprocess() {');

  for (final step in manifest.preprocessing) {
    switch (step) {
      case RescaleStep(:final factor, :final offset):
        b
          ..writeln('    // rescale: v * $factor + $offset')
          ..writeln('    {')
          ..writeln('      final v = values;')
          ..writeln('      for (var i = 0; i < v.length; i++) {')
          ..writeln('        v[i] = v[i] * $factor + $offset;')
          ..writeln('      }')
          ..writeln('    }');
      case NormalizeStep(:final mean, :final std, :final axis):
        final channels = mean.length;
        final resolved = axis < 0 ? spec.rank + axis : axis;
        final stride = _strideOf(spec, resolved);
        b
          ..writeln('    // normalize over axis $resolved, $channels channels')
          ..writeln('    {')
          ..writeln('      const mean = [${mean.join(', ')}];')
          ..writeln('      const std = [${std.join(', ')}];')
          ..writeln('      final v = values;')
          ..writeln('      for (var i = 0; i < v.length; i++) {')
          ..writeln('        final c = (i ~/ $stride) % $channels;')
          ..writeln('        v[i] = (v[i] - mean[c]) / std[c];')
          ..writeln('      }')
          ..writeln('    }');
      case CastStep(:final target):
        b.writeln(
          '    // cast to $target: already the tensor\'s type, nothing to do',
        );
      case ResizeStep() || CenterCropStep() || UnknownPreprocessingStep():
        // checkGeneratable refuses these, so reaching here is a defect in it.
        throw StateError(
          '${step.kind} should have been refused before emitting',
        );
    }
  }

  b
    ..writeln('  }')
    ..writeln('}')
    ..writeln();
}

/// Elements between consecutive values along [axis], for a contiguous tensor.
int _strideOf(TensorSpec spec, int axis) {
  var stride = 1;
  for (var i = spec.rank - 1; i > axis; i--) {
    stride *= spec.shape[i];
  }
  return stride;
}

// ── outputs ────────────────────────────────────────────────────────────────────

void _outputsClass(StringBuffer b, String model, ModelManifest manifest) {
  b
    ..writeln('/// What [$model.run] returns.')
    ..writeln('final class ${model}Outputs {')
    ..writeln('  const ${model}Outputs._(this._tensors);')
    ..writeln()
    ..writeln('  final List<Tensor> _tensors;')
    ..writeln();
  for (final (i, spec) in manifest.outputs.indexed) {
    final type = _typeName(model, spec);
    b
      ..writeln('  /// The `${spec.name}` output.')
      ..writeln('  $type get ${camelCase(spec.name)} => $type._(_tensors[$i]);')
      ..writeln();
  }
  if (manifest.labels != null) {
    b
      ..writeln('  /// The class labels the export recorded, in order.')
      ..writeln('  static const List<String> labels = [')
      ..writeln(manifest.labels!.map((l) => "    '${_escape(l)}',").join('\n'))
      ..writeln('  ];')
      ..writeln();
  }
  b
    ..writeln('  /// Every output, positional with the manifest.')
    ..writeln('  List<Tensor> get tensors => List.unmodifiable(_tensors);')
    ..writeln('}')
    ..writeln();
}

// ── the model ──────────────────────────────────────────────────────────────────

void _modelClass(
  StringBuffer b,
  String model,
  ModelManifest manifest,
  String sourceName,
) {
  final inputs = manifest.inputs;
  final params = inputs
      .map((s) => 'required ${_typeName(model, s)} ${camelCase(s.name)}')
      .join(', ');
  final args = inputs.map((s) => '${camelCase(s.name)}.tensor').join(', ');

  b
    ..writeln('/// `${manifest.name}`, as exported.')
    ..writeln('///')
    ..writeln(
      '/// Carries its own manifest, so loading verifies the artifact against',
    )
    ..writeln(
      '/// the contract it was generated from without any separate plumbing.',
    )
    ..writeln('final class $model {')
    ..writeln('  const $model._(this.model);')
    ..writeln()
    ..writeln(
      '  /// The loaded model this wraps, for anything the generated API',
    )
    ..writeln('  /// does not cover.')
    ..writeln('  final LoadedModel model;')
    ..writeln()
    ..writeln(
      '  /// The manifest this class was generated from, embedded verbatim.',
    )
    ..writeln('  static const String manifestJson = r\'\'\'')
    ..write(ManifestCodec.encode(manifest))
    ..writeln('\'\'\';')
    ..writeln()
    ..writeln('  static ModelManifest? _manifest;')
    ..writeln()
    ..writeln('  /// The contract, parsed once.')
    ..writeln('  static ModelManifest get manifest =>')
    ..writeln('      _manifest ??= ManifestCodec.decode(manifestJson);')
    ..writeln()
    ..writeln('  /// Digest of the artifact this class was generated for.')
    ..writeln("  static const String weightHash = '${manifest.weightHash}';")
    ..writeln()
    ..writeln(
      '  /// Loads [artifact] on [runtime], refusing one that does not match',
    )
    ..writeln('  /// [weightHash].')
    ..writeln('  ///')
    ..writeln(
      '  /// The check is not optional: an artifact paired with the wrong',
    )
    ..writeln(
      '  /// contract satisfies every shape and returns every number wrong.',
    )
    ..writeln('  static Future<$model> load(')
    ..writeln('    FluttorchRuntime runtime, {')
    ..writeln('    required Uint8List artifact,')
    ..writeln('    String? backend,')
    ..writeln('  }) async {')
    ..writeln('    verifyArtifact(artifact: artifact, manifest: manifest);')
    ..writeln('    return $model._(await runtime.load(')
    ..writeln('      artifact: artifact,')
    ..writeln('      manifest: manifest,')
    ..writeln('      backend: backend,')
    ..writeln('    ));')
    ..writeln('  }')
    ..writeln()
    ..writeln(
      '  /// Wraps a model loaded through some other path — an isolate,',
    )
    ..writeln('  /// a cache, a pool — checking that it is this model.')
    ..writeln('  ///')
    ..writeln(
      '  /// Throws [ArtifactMismatchException] if the loaded model was',
    )
    ..writeln('  /// built from a different export.')
    ..writeln('  factory $model.wrap(LoadedModel loaded) {')
    ..writeln('    if (loaded.manifest.weightHash != weightHash) {')
    ..writeln('      throw ArtifactMismatchException(')
    ..writeln('        expectedHash: weightHash,')
    ..writeln('        actualHash: loaded.manifest.weightHash,')
    ..writeln('      );')
    ..writeln('    }')
    ..writeln('    return $model._(loaded);')
    ..writeln('  }')
    ..writeln()
    ..writeln('  /// Runs inference.')
    ..writeln('  ///')
    ..writeln(
      '  /// The parameter types are what makes a wrong tensor a compile',
    )
    ..writeln(
      '  /// error; nothing here can be called with the arguments in the',
    )
    ..writeln('  /// wrong order.')
    ..writeln('  Future<${model}Outputs> run({$params}) async =>')
    ..writeln('      ${model}Outputs._(await model.run([$args]));')
    ..writeln()
    ..writeln('  /// Releases the native resources behind the model.')
    ..writeln('  Future<void> dispose() => model.dispose();')
    ..writeln('}')
    ..writeln();
}

// ── helpers ────────────────────────────────────────────────────────────────────

String? _listType(DType dtype) => switch (dtype) {
  DType.float32 => 'Float32List',
  DType.float64 => 'Float64List',
  DType.int8 => 'Int8List',
  DType.int16 => 'Int16List',
  DType.int32 => 'Int32List',
  DType.int64 => 'Int64List',
  DType.uint8 || DType.boolean => 'Uint8List',
  DType.float16 || DType.bfloat16 => null,
};

String _viewCall(DType dtype) => switch (dtype) {
  DType.float32 => 'asFloat32List()',
  DType.float64 => 'asFloat64List()',
  DType.int8 => 'asInt8List()',
  DType.int16 => 'asInt16List()',
  DType.int32 => 'asInt32List()',
  DType.int64 => 'asInt64List()',
  DType.uint8 || DType.boolean => 'asUint8List()',
  DType.float16 || DType.bfloat16 => 'bytes',
};

String _escape(String s) => s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
