@TestOn('vm')
library;

import 'dart:io';

import 'package:fluttorch/fluttorch.dart';
import 'package:fluttorch_gen/fluttorch_gen.dart';
import 'package:test/test.dart';

/// The generated API for the committed export, pinned.
///
/// It is also compiled: `test/golden/two_layer.fluttorch.dart` is real Dart in a
/// package CI analyses, so a generator that emits something that does not
/// compile fails the build rather than the diff.
final _golden = File('test/golden/two_layer.fluttorch.dart');
final _manifestFile = File('../../testdata/two_layer/two_layer.fluttorch.json');

const _image = TensorSpec(
  name: 'image',
  dtype: DType.float32,
  shape: [1, 3, 8, 8],
  layout: TensorLayout.nchw,
);

ModelManifest manifestWith({
  List<PreprocessingStep> preprocessing = const [],
  List<TensorSpec>? inputs,
  List<TensorSpec>? outputs,
  List<String>? labels,
  String name = 'demo',
}) => ModelManifest(
  name: name,
  schemaVersion: ModelManifest.currentSchemaVersion,
  weightHash: 'sha256:${'0' * 64}',
  inputs:
      inputs ??
      const [
        TensorSpec(name: 'x', dtype: DType.float32, shape: [1, 4]),
      ],
  outputs:
      outputs ??
      const [
        TensorSpec(name: 'y', dtype: DType.float32, shape: [1, 2]),
      ],
  preprocessing: preprocessing,
  labels: labels,
);

void main() {
  group('M12 · the generator output is pinned', () {
    test('the committed golden is what the emitter produces', () {
      final manifest = ManifestCodec.decode(_manifestFile.readAsStringSync());
      final produced = emit(manifest, sourceName: 'two_layer.fluttorch.json');

      if (Platform.environment['UPDATE_GOLDENS'] == '1') {
        _golden.writeAsStringSync(produced);
        markTestSkipped('golden rewritten; re-run without UPDATE_GOLDENS');
        return;
      }

      // dart format runs over the repository, so compare against the formatted
      // form rather than asserting the emitter's own whitespace.
      expect(
        _normalise(produced),
        _normalise(_golden.readAsStringSync()),
        reason:
            'regenerate with UPDATE_GOLDENS=1 and check the diff is intended',
      );
    });

    test(
      'the golden carries the hash of the artifact it was generated for',
      () {
        final manifest = ManifestCodec.decode(_manifestFile.readAsStringSync());
        expect(_golden.readAsStringSync(), contains(manifest.weightHash));
      },
    );
  });

  group('M9 · what the generated class carries', () {
    late String source;

    setUpAll(() {
      source = emit(
        ManifestCodec.decode(_manifestFile.readAsStringSync()),
        sourceName: 'two_layer.fluttorch.json',
      );
    });

    test('a class named after the model', () {
      expect(source, contains('final class TwoLayer {'));
      expect(source, contains('final class TwoLayerOutputs {'));
    });

    test('one type per tensor, named after it', () {
      expect(source, contains('extension type const TwoLayerFeatures._'));
      expect(source, contains('extension type const TwoLayerScore._'));
    });

    test('the spec each tensor was declared with', () {
      expect(source, contains("name: 'features'"));
      expect(source, contains('dtype: DType.float32'));
      expect(source, contains('shape: [1, 4]'));
    });

    test('the labels, in order', () {
      expect(
        source,
        contains("static const List<String> labels = ['low', 'mid', 'high']"),
      );
    });

    test('the manifest verbatim, so loading needs no separate plumbing', () {
      expect(source, contains('static const String manifestJson'));
      expect(source, contains('verifyArtifact('));
    });

    test('it says not to edit it, and why', () {
      expect(source, startsWith('// GENERATED BY fluttorch_gen'));
      expect(source, contains('disagree with the export'));
    });
  });

  group('a model with more than one output', () {
    // Until `testdata/multi_io` there was no export that returned two tensors,
    // so this loop had only ever emitted index 0 and the accessor for a second
    // output had never been written, let alone called. The behaviour is pinned
    // end to end in examples/typed_api, which runs the generated code against
    // two tensors it can tell apart; this is the same claim one layer down,
    // where whoever changes the emitter will see it first.
    const outputs = [
      TensorSpec(name: 'primary', dtype: DType.float32, shape: [1, 3]),
      TensorSpec(name: 'auxiliary', dtype: DType.float32, shape: [1, 3]),
    ];

    test('each accessor reads its own position', () {
      final source = emit(
        manifestWith(outputs: outputs),
        sourceName: 'demo.fluttorch.json',
      );

      expect(
        source,
        contains('DemoPrimary get primary => DemoPrimary._(_tensors[0]);'),
      );
      expect(
        source,
        contains(
          'DemoAuxiliary get auxiliary => DemoAuxiliary._(_tensors[1]);',
        ),
      );
    });

    test('one type per output, even where the shapes agree', () {
      final source = emit(
        manifestWith(outputs: outputs),
        sourceName: 'demo.fluttorch.json',
      );

      // Same dtype and same shape, so nothing but the name separates them. A
      // generator that keyed off the spec rather than the declaration would
      // emit one type here and the two outputs would become interchangeable.
      expect(source, contains('extension type const DemoPrimary._'));
      expect(source, contains('extension type const DemoAuxiliary._'));
    });
  });

  group('M10 · preprocessing is generated, never hand-written', () {
    test('a rescale becomes the arithmetic it describes', () {
      final source = emit(
        manifestWith(
          preprocessing: const [RescaleStep(factor: 0.5, offset: 1)],
        ),
        sourceName: 'demo.fluttorch.json',
      );
      expect(source, contains('extension DemoXPreprocessing on DemoX'));
      expect(source, contains('v[i] = v[i] * 0.5 + 1.0;'));
    });

    test('a normalize carries the exact constants training used', () {
      final source = emit(
        manifestWith(
          preprocessing: const [
            NormalizeStep(mean: [0.5, 0.25], std: [0.2, 0.1], axis: -1),
          ],
          inputs: const [
            TensorSpec(name: 'x', dtype: DType.float32, shape: [1, 2]),
          ],
        ),
        sourceName: 'demo.fluttorch.json',
      );
      expect(source, contains('const mean = [0.5, 0.25];'));
      expect(source, contains('const std = [0.2, 0.1];'));
      expect(source, contains('(i ~/ 1) % 2'), reason: 'innermost axis');
    });

    test('the channel stride follows the axis it was recorded on', () {
      final source = emit(
        manifestWith(
          preprocessing: const [
            NormalizeStep(mean: [0, 0, 0], std: [1, 1, 1], axis: 1),
          ],
          inputs: const [
            TensorSpec(name: 'x', dtype: DType.float32, shape: [1, 3, 4, 5]),
          ],
        ),
        sourceName: 'demo.fluttorch.json',
      );
      // NCHW: 20 elements between consecutive channels.
      expect(source, contains('(i ~/ 20) % 3'));
    });

    test('no preprocessing means no extension at all', () {
      final source = emit(manifestWith(), sourceName: 'demo.fluttorch.json');
      expect(source, isNot(contains('Preprocessing on')));
    });
  });

  group('a manifest that cannot be generated from is refused', () {
    void expectRefused(ModelManifest m, String reason) {
      expect(
        () => emit(m, sourceName: 'demo.fluttorch.json'),
        throwsA(
          isA<UnsupportedManifestException>().having(
            (e) => e.reasons.join(' '),
            'reasons',
            contains(reason),
          ),
        ),
      );
    }

    test('a step this build does not understand', () {
      expectRefused(
        manifestWith(
          preprocessing: const [
            UnknownPreprocessingStep(kind: 'mel_spectrogram', params: {}),
          ],
        ),
        'silently drop',
      );
    });

    test('a resize, because the input declares no layout', () {
      // Understood and still not generatable: performing it means knowing which
      // axes are spatial, and NCHW and NHWC each give a plausible wrong answer.
      expectRefused(
        manifestWith(preprocessing: const [ResizeStep(height: 8, width: 8)]),
        'declares no layout',
      );
    });

    test('a resize whose filter this generator does not emit', () {
      // Named rather than approximated. Bicubic needs a four-tap kernel whose
      // coefficient torch and PIL disagree about, so substituting bilinear
      // would reproduce a resize that runs and is not the one training used.
      expectRefused(
        manifestWith(
          inputs: const [_image],
          preprocessing: const [
            ResizeStep(height: 8, width: 8, interpolation: 'bicubic'),
          ],
        ),
        'is not the one training applied',
      );
    });

    test('a spatial step after an elementwise one', () {
      // Refused rather than reordered. Bilinear resize and an affine rescale
      // commute in exact arithmetic, which is what makes silently reordering
      // them look safe: the rounding of either, or a cast between them, moves
      // the result by an amount nobody would go looking for.
      expectRefused(
        manifestWith(
          inputs: const [_image],
          preprocessing: const [
            RescaleStep(factor: 1 / 255),
            ResizeStep(height: 8, width: 8),
          ],
        ),
        'silently reorder',
      );
    });

    test('spatial steps against a model with more than one input', () {
      expectRefused(
        manifestWith(
          inputs: const [
            _image,
            TensorSpec(name: 'meta', dtype: DType.float32, shape: [1, 2]),
          ],
          preprocessing: const [ResizeStep(height: 8, width: 8)],
        ),
        'no way to tell which one they apply to',
      );
    });

    test('a crop, for the same reason', () {
      expectRefused(
        manifestWith(
          preprocessing: const [CenterCropStep(height: 4, width: 4)],
        ),
        'declares no layout',
      );
    });

    test('a normalize on a model with more than one input', () {
      expectRefused(
        manifestWith(
          preprocessing: const [
            NormalizeStep(mean: [0], std: [1]),
          ],
          inputs: const [
            TensorSpec(name: 'a', dtype: DType.float32, shape: [1]),
            TensorSpec(name: 'b', dtype: DType.float32, shape: [1]),
          ],
        ),
        'which one it applies to',
      );
    });
  });

  group('names that are legal in a manifest and not in Dart', () {
    test('a leading digit is refused rather than mangled', () {
      expect(
        () => emit(
          manifestWith(
            inputs: const [
              TensorSpec(name: '2nd_input', dtype: DType.float32, shape: [1]),
            ],
          ),
          sourceName: 'demo.fluttorch.json',
        ),
        throwsA(
          isA<UnusableNameException>().having(
            (e) => e.reason,
            'reason',
            contains('starts with a digit'),
          ),
        ),
      );
    });

    test('two names that collapse to one accessor are refused', () {
      expect(
        () => emit(
          manifestWith(
            inputs: const [
              TensorSpec(name: 'load_mw', dtype: DType.float32, shape: [1]),
              TensorSpec(name: 'load.mw', dtype: DType.float32, shape: [1]),
            ],
          ),
          sourceName: 'demo.fluttorch.json',
        ),
        throwsA(
          isA<UnusableNameException>().having(
            (e) => e.reason,
            'reason',
            contains('both become "loadMw"'),
          ),
        ),
      );
    });

    test('a Dart keyword gets a trailing underscore', () {
      final source = emit(
        manifestWith(
          outputs: const [
            TensorSpec(name: 'class', dtype: DType.float32, shape: [1]),
          ],
        ),
        sourceName: 'demo.fluttorch.json',
      );
      expect(source, contains('get class_ =>'));
    });
  });

  group('M11 · dynamic dimensions get the escape hatch, and only that', () {
    test('a fixed tensor gets a checked list constructor', () {
      final source = emit(manifestWith(), sourceName: 'demo.fluttorch.json');
      expect(source, contains('factory DemoX(Float32List values)'));
      expect(source, contains('values.length != 4'));
      expect(source, isNot(contains('DemoX.withShape')));
    });

    test('a dynamic tensor gets withShape instead, and it says why', () {
      final source = emit(
        manifestWith(
          inputs: const [
            TensorSpec(
              name: 'x',
              dtype: DType.float32,
              shape: [TensorSpec.dynamicDim, 4],
            ),
          ],
        ),
        sourceName: 'demo.fluttorch.json',
      );
      expect(source, contains('factory DemoX.withShape('));
      expect(source, contains('cannot be checked by the compiler'));
      expect(source, isNot(contains('factory DemoX(Float32List')));
    });

    test('a type with no Dart list view exposes bytes instead', () {
      final source = emit(
        manifestWith(
          outputs: const [
            TensorSpec(name: 'y', dtype: DType.bfloat16, shape: [4]),
          ],
        ),
        sourceName: 'demo.fluttorch.json',
      );
      expect(source, contains('Uint8List get bytes'));
      expect(source, isNot(contains('Float16List')));
    });
  });
}

/// Compare on content rather than on the formatter's line breaks.
String _normalise(String source) =>
    source.replaceAll(RegExp(r'\s+'), ' ').trim();
