// GENERATED BY fluttorch_gen — do not edit.
//
// Source: voltacast.fluttorch.json
// Manifest schema 1
// Weights: sha256:1d1bbd9883394114359491ade45a3a04b06022026a16cb7160b818b67a1bef02
//
// Editing this file lets the Dart side disagree with the export it
// came from, which is the failure this generator exists to prevent.
// Change the model, re-export, and rebuild.

// ignore_for_file: unnecessary_cast, unused_import

import 'dart:typed_data';

import 'package:fluttorch/fluttorch.dart';

/// The `past` input: `float32[1, 168, 13]`.
///
/// A distinct type rather than a bare [Tensor], so passing the wrong
/// tensor to [Voltacast.run] is a compile error rather than a shape
/// mismatch discovered at inference. The wrapper costs nothing at
/// run time.
extension type const VoltacastPast._(Tensor tensor) {
  /// What the export declared for this tensor.
  static const TensorSpec spec = TensorSpec(
    name: 'past',
    dtype: DType.float32,
    shape: [1, 168, 13],
  );

  /// Wraps 2184 `float32` values.
  ///
  /// Throws [TensorShapeException] unless [values] holds exactly
  /// 2184; the shape itself is fixed by the export.
  factory VoltacastPast(Float32List values) {
    if (values.length != 2184) {
      throw TensorShapeException(
        'expected 2184 values, got ${values.length}',
        tensorName: 'past',
      );
    }
    return VoltacastPast._(
      Tensor.view(
        spec: spec,
        bytes: values.buffer.asUint8List(
          values.offsetInBytes,
          values.lengthInBytes,
        ),
      ),
    );
  }

  /// An all-zero tensor, for use as a destination buffer.
  factory VoltacastPast.zeros() => VoltacastPast._(Tensor.zeros(spec));

  /// Wraps a tensor that already satisfies [spec].
  ///
  /// Throws [TensorShapeException] or [DTypeMismatchException] if it
  /// does not.
  factory VoltacastPast.wrap(Tensor tensor) {
    checkTensorsAgainst([spec], [tensor], role: 'past');
    return VoltacastPast._(tensor);
  }

  /// The values, over the same memory. No copy is made.
  Float32List get values => tensor.asFloat32List();

  /// The concrete shape, which for a dynamic spec is known only here.
  List<int> get shape => tensor.shape;
}

/// The `future` input: `float32[1, 24, 12]`.
///
/// A distinct type rather than a bare [Tensor], so passing the wrong
/// tensor to [Voltacast.run] is a compile error rather than a shape
/// mismatch discovered at inference. The wrapper costs nothing at
/// run time.
extension type const VoltacastFuture._(Tensor tensor) {
  /// What the export declared for this tensor.
  static const TensorSpec spec = TensorSpec(
    name: 'future',
    dtype: DType.float32,
    shape: [1, 24, 12],
  );

  /// Wraps 288 `float32` values.
  ///
  /// Throws [TensorShapeException] unless [values] holds exactly
  /// 288; the shape itself is fixed by the export.
  factory VoltacastFuture(Float32List values) {
    if (values.length != 288) {
      throw TensorShapeException(
        'expected 288 values, got ${values.length}',
        tensorName: 'future',
      );
    }
    return VoltacastFuture._(
      Tensor.view(
        spec: spec,
        bytes: values.buffer.asUint8List(
          values.offsetInBytes,
          values.lengthInBytes,
        ),
      ),
    );
  }

  /// An all-zero tensor, for use as a destination buffer.
  factory VoltacastFuture.zeros() => VoltacastFuture._(Tensor.zeros(spec));

  /// Wraps a tensor that already satisfies [spec].
  ///
  /// Throws [TensorShapeException] or [DTypeMismatchException] if it
  /// does not.
  factory VoltacastFuture.wrap(Tensor tensor) {
    checkTensorsAgainst([spec], [tensor], role: 'future');
    return VoltacastFuture._(tensor);
  }

  /// The values, over the same memory. No copy is made.
  Float32List get values => tensor.asFloat32List();

  /// The concrete shape, which for a dynamic spec is known only here.
  List<int> get shape => tensor.shape;
}

/// The `quantiles` output: `float32[1, 24, 3]`.
///
/// A distinct type rather than a bare [Tensor], so passing the wrong
/// tensor to [Voltacast.run] is a compile error rather than a shape
/// mismatch discovered at inference. The wrapper costs nothing at
/// run time.
extension type const VoltacastQuantiles._(Tensor tensor) {
  /// What the export declared for this tensor.
  static const TensorSpec spec = TensorSpec(
    name: 'quantiles',
    dtype: DType.float32,
    shape: [1, 24, 3],
  );

  /// Wraps 72 `float32` values.
  ///
  /// Throws [TensorShapeException] unless [values] holds exactly
  /// 72; the shape itself is fixed by the export.
  factory VoltacastQuantiles(Float32List values) {
    if (values.length != 72) {
      throw TensorShapeException(
        'expected 72 values, got ${values.length}',
        tensorName: 'quantiles',
      );
    }
    return VoltacastQuantiles._(
      Tensor.view(
        spec: spec,
        bytes: values.buffer.asUint8List(
          values.offsetInBytes,
          values.lengthInBytes,
        ),
      ),
    );
  }

  /// An all-zero tensor, for use as a destination buffer.
  factory VoltacastQuantiles.zeros() =>
      VoltacastQuantiles._(Tensor.zeros(spec));

  /// Wraps a tensor that already satisfies [spec].
  ///
  /// Throws [TensorShapeException] or [DTypeMismatchException] if it
  /// does not.
  factory VoltacastQuantiles.wrap(Tensor tensor) {
    checkTensorsAgainst([spec], [tensor], role: 'quantiles');
    return VoltacastQuantiles._(tensor);
  }

  /// The values, over the same memory. No copy is made.
  Float32List get values => tensor.asFloat32List();

  /// The concrete shape, which for a dynamic spec is known only here.
  List<int> get shape => tensor.shape;
}

/// What [Voltacast.run] returns.
final class VoltacastOutputs {
  const VoltacastOutputs._(this._tensors);

  final List<Tensor> _tensors;

  /// The `quantiles` output.
  VoltacastQuantiles get quantiles => VoltacastQuantiles._(_tensors[0]);

  /// The class labels the export recorded, in order.
  static const List<String> labels = ['p10', 'p50', 'p90'];

  /// Every output, positional with the manifest.
  List<Tensor> get tensors => List.unmodifiable(_tensors);
}

/// `voltacast`, as exported.
///
/// Carries its own manifest, so loading verifies the artifact against
/// the contract it was generated from without any separate plumbing.
final class Voltacast {
  const Voltacast._(this.model);

  /// The loaded model this wraps, for anything the generated API
  /// does not cover.
  final LoadedModel model;

  /// The manifest this class was generated from, embedded verbatim.
  static const String manifestJson = r'''
{
  "schema_version": 1,
  "name": "voltacast",
  "weight_hash": "sha256:1d1bbd9883394114359491ade45a3a04b06022026a16cb7160b818b67a1bef02",
  "inputs": [
    {
      "name": "past",
      "dtype": "float32",
      "shape": [
        1,
        168,
        13
      ]
    },
    {
      "name": "future",
      "dtype": "float32",
      "shape": [
        1,
        24,
        12
      ]
    }
  ],
  "outputs": [
    {
      "name": "quantiles",
      "dtype": "float32",
      "shape": [
        1,
        24,
        3
      ]
    }
  ],
  "labels": [
    "p10",
    "p50",
    "p90"
  ],
  "goldens": [
    {
      "id": "case-0",
      "inputs": [
        "0/in/past.bin",
        "0/in/future.bin"
      ],
      "outputs": [
        "0/out/quantiles.bin"
      ]
    },
    {
      "id": "case-1",
      "inputs": [
        "1/in/past.bin",
        "1/in/future.bin"
      ],
      "outputs": [
        "1/out/quantiles.bin"
      ]
    },
    {
      "id": "case-2",
      "inputs": [
        "2/in/past.bin",
        "2/in/future.bin"
      ],
      "outputs": [
        "2/out/quantiles.bin"
      ]
    },
    {
      "id": "case-3",
      "inputs": [
        "3/in/past.bin",
        "3/in/future.bin"
      ],
      "outputs": [
        "3/out/quantiles.bin"
      ]
    }
  ]
}
''';

  static ModelManifest? _manifest;

  /// The contract, parsed once.
  static ModelManifest get manifest =>
      _manifest ??= ManifestCodec.decode(manifestJson);

  /// Digest of the artifact this class was generated for.
  static const String weightHash =
      'sha256:1d1bbd9883394114359491ade45a3a04b06022026a16cb7160b818b67a1bef02';

  /// Loads [artifact] on [runtime], refusing one that does not match
  /// [weightHash].
  ///
  /// The check is not optional: an artifact paired with the wrong
  /// contract satisfies every shape and returns every number wrong.
  static Future<Voltacast> load(
    FluttorchRuntime runtime, {
    required Uint8List artifact,
    String? backend,
  }) async {
    verifyArtifact(artifact: artifact, manifest: manifest);
    return Voltacast._(
      await runtime.load(
        artifact: artifact,
        manifest: manifest,
        backend: backend,
      ),
    );
  }

  /// Wraps a model loaded through some other path — an isolate,
  /// a cache, a pool — checking that it is this model.
  ///
  /// Throws [ArtifactMismatchException] if the loaded model was
  /// built from a different export.
  factory Voltacast.wrap(LoadedModel loaded) {
    if (loaded.manifest.weightHash != weightHash) {
      throw ArtifactMismatchException(
        expectedHash: weightHash,
        actualHash: loaded.manifest.weightHash,
      );
    }
    return Voltacast._(loaded);
  }

  /// Runs inference.
  ///
  /// The parameter types are what makes a wrong tensor a compile
  /// error; nothing here can be called with the arguments in the
  /// wrong order.
  Future<VoltacastOutputs> run({
    required VoltacastPast past,
    required VoltacastFuture future,
  }) async => VoltacastOutputs._(await model.run([past.tensor, future.tensor]));

  /// Releases the native resources behind the model.
  Future<void> dispose() => model.dispose();
}
