// GENERATED BY fluttorch_gen — do not edit.
//
// Source: multi_io.fluttorch.json
// Manifest schema 1
// Weights: sha256:c5805f1ce29c3d33620d445ec42f8dfd47ab3f8956a647ec5823f5ede46bf9c7
//
// Editing this file lets the Dart side disagree with the export it
// came from, which is the failure this generator exists to prevent.
// Change the model, re-export, and rebuild.

// ignore_for_file: unnecessary_cast, unused_import

import 'dart:typed_data';

import 'package:fluttorch/fluttorch.dart';

/// The `left` input: `float32[1, 5]`.
///
/// A distinct type rather than a bare [Tensor], so passing the wrong
/// tensor to [MultiIo.run] is a compile error rather than a shape
/// mismatch discovered at inference. The wrapper costs nothing at
/// run time.
extension type const MultiIoLeft._(Tensor tensor) {
  /// What the export declared for this tensor.
  static const TensorSpec spec = TensorSpec(
    name: 'left',
    dtype: DType.float32,
    shape: [1, 5],
  );

  /// Wraps 5 `float32` values.
  ///
  /// Throws [TensorShapeException] unless [values] holds exactly
  /// 5; the shape itself is fixed by the export.
  factory MultiIoLeft(Float32List values) {
    if (values.length != 5) {
      throw TensorShapeException(
        'expected 5 values, got ${values.length}',
        tensorName: 'left',
      );
    }
    return MultiIoLeft._(
      Tensor.view(
        spec: spec,
        bytes: values.buffer.asUint8List(
          values.offsetInBytes,
          values.lengthInBytes,
        ),
      ),
    );
  }

  /// An all-zero tensor, for use as a destination buffer.
  factory MultiIoLeft.zeros() => MultiIoLeft._(Tensor.zeros(spec));

  /// Wraps a tensor that already satisfies [spec].
  ///
  /// Throws [TensorShapeException] or [DTypeMismatchException] if it
  /// does not.
  factory MultiIoLeft.wrap(Tensor tensor) {
    checkTensorsAgainst([spec], [tensor], role: 'left');
    return MultiIoLeft._(tensor);
  }

  /// The values, over the same memory. No copy is made.
  Float32List get values => tensor.asFloat32List();

  /// The concrete shape, which for a dynamic spec is known only here.
  List<int> get shape => tensor.shape;
}

/// The `right` input: `float32[1, 5]`.
///
/// A distinct type rather than a bare [Tensor], so passing the wrong
/// tensor to [MultiIo.run] is a compile error rather than a shape
/// mismatch discovered at inference. The wrapper costs nothing at
/// run time.
extension type const MultiIoRight._(Tensor tensor) {
  /// What the export declared for this tensor.
  static const TensorSpec spec = TensorSpec(
    name: 'right',
    dtype: DType.float32,
    shape: [1, 5],
  );

  /// Wraps 5 `float32` values.
  ///
  /// Throws [TensorShapeException] unless [values] holds exactly
  /// 5; the shape itself is fixed by the export.
  factory MultiIoRight(Float32List values) {
    if (values.length != 5) {
      throw TensorShapeException(
        'expected 5 values, got ${values.length}',
        tensorName: 'right',
      );
    }
    return MultiIoRight._(
      Tensor.view(
        spec: spec,
        bytes: values.buffer.asUint8List(
          values.offsetInBytes,
          values.lengthInBytes,
        ),
      ),
    );
  }

  /// An all-zero tensor, for use as a destination buffer.
  factory MultiIoRight.zeros() => MultiIoRight._(Tensor.zeros(spec));

  /// Wraps a tensor that already satisfies [spec].
  ///
  /// Throws [TensorShapeException] or [DTypeMismatchException] if it
  /// does not.
  factory MultiIoRight.wrap(Tensor tensor) {
    checkTensorsAgainst([spec], [tensor], role: 'right');
    return MultiIoRight._(tensor);
  }

  /// The values, over the same memory. No copy is made.
  Float32List get values => tensor.asFloat32List();

  /// The concrete shape, which for a dynamic spec is known only here.
  List<int> get shape => tensor.shape;
}

/// The `primary` output: `float32[1, 3]`.
///
/// A distinct type rather than a bare [Tensor], so passing the wrong
/// tensor to [MultiIo.run] is a compile error rather than a shape
/// mismatch discovered at inference. The wrapper costs nothing at
/// run time.
extension type const MultiIoPrimary._(Tensor tensor) {
  /// What the export declared for this tensor.
  static const TensorSpec spec = TensorSpec(
    name: 'primary',
    dtype: DType.float32,
    shape: [1, 3],
  );

  /// Wraps 3 `float32` values.
  ///
  /// Throws [TensorShapeException] unless [values] holds exactly
  /// 3; the shape itself is fixed by the export.
  factory MultiIoPrimary(Float32List values) {
    if (values.length != 3) {
      throw TensorShapeException(
        'expected 3 values, got ${values.length}',
        tensorName: 'primary',
      );
    }
    return MultiIoPrimary._(
      Tensor.view(
        spec: spec,
        bytes: values.buffer.asUint8List(
          values.offsetInBytes,
          values.lengthInBytes,
        ),
      ),
    );
  }

  /// An all-zero tensor, for use as a destination buffer.
  factory MultiIoPrimary.zeros() => MultiIoPrimary._(Tensor.zeros(spec));

  /// Wraps a tensor that already satisfies [spec].
  ///
  /// Throws [TensorShapeException] or [DTypeMismatchException] if it
  /// does not.
  factory MultiIoPrimary.wrap(Tensor tensor) {
    checkTensorsAgainst([spec], [tensor], role: 'primary');
    return MultiIoPrimary._(tensor);
  }

  /// The values, over the same memory. No copy is made.
  Float32List get values => tensor.asFloat32List();

  /// The concrete shape, which for a dynamic spec is known only here.
  List<int> get shape => tensor.shape;
}

/// The `auxiliary` output: `float32[1, 3]`.
///
/// A distinct type rather than a bare [Tensor], so passing the wrong
/// tensor to [MultiIo.run] is a compile error rather than a shape
/// mismatch discovered at inference. The wrapper costs nothing at
/// run time.
extension type const MultiIoAuxiliary._(Tensor tensor) {
  /// What the export declared for this tensor.
  static const TensorSpec spec = TensorSpec(
    name: 'auxiliary',
    dtype: DType.float32,
    shape: [1, 3],
  );

  /// Wraps 3 `float32` values.
  ///
  /// Throws [TensorShapeException] unless [values] holds exactly
  /// 3; the shape itself is fixed by the export.
  factory MultiIoAuxiliary(Float32List values) {
    if (values.length != 3) {
      throw TensorShapeException(
        'expected 3 values, got ${values.length}',
        tensorName: 'auxiliary',
      );
    }
    return MultiIoAuxiliary._(
      Tensor.view(
        spec: spec,
        bytes: values.buffer.asUint8List(
          values.offsetInBytes,
          values.lengthInBytes,
        ),
      ),
    );
  }

  /// An all-zero tensor, for use as a destination buffer.
  factory MultiIoAuxiliary.zeros() => MultiIoAuxiliary._(Tensor.zeros(spec));

  /// Wraps a tensor that already satisfies [spec].
  ///
  /// Throws [TensorShapeException] or [DTypeMismatchException] if it
  /// does not.
  factory MultiIoAuxiliary.wrap(Tensor tensor) {
    checkTensorsAgainst([spec], [tensor], role: 'auxiliary');
    return MultiIoAuxiliary._(tensor);
  }

  /// The values, over the same memory. No copy is made.
  Float32List get values => tensor.asFloat32List();

  /// The concrete shape, which for a dynamic spec is known only here.
  List<int> get shape => tensor.shape;
}

/// What [MultiIo.run] returns.
final class MultiIoOutputs {
  const MultiIoOutputs._(this._tensors);

  final List<Tensor> _tensors;

  /// The `primary` output.
  MultiIoPrimary get primary => MultiIoPrimary._(_tensors[0]);

  /// The `auxiliary` output.
  MultiIoAuxiliary get auxiliary => MultiIoAuxiliary._(_tensors[1]);

  /// Every output, positional with the manifest.
  List<Tensor> get tensors => List.unmodifiable(_tensors);
}

/// `multi_io`, as exported.
///
/// Carries its own manifest, so loading verifies the artifact against
/// the contract it was generated from without any separate plumbing.
final class MultiIo {
  const MultiIo._(this.model);

  /// The loaded model this wraps, for anything the generated API
  /// does not cover.
  final LoadedModel model;

  /// The manifest this class was generated from, embedded verbatim.
  static const String manifestJson = r'''
{
  "schema_version": 1,
  "name": "multi_io",
  "weight_hash": "sha256:c5805f1ce29c3d33620d445ec42f8dfd47ab3f8956a647ec5823f5ede46bf9c7",
  "inputs": [
    {
      "name": "left",
      "dtype": "float32",
      "shape": [
        1,
        5
      ]
    },
    {
      "name": "right",
      "dtype": "float32",
      "shape": [
        1,
        5
      ]
    }
  ],
  "outputs": [
    {
      "name": "primary",
      "dtype": "float32",
      "shape": [
        1,
        3
      ]
    },
    {
      "name": "auxiliary",
      "dtype": "float32",
      "shape": [
        1,
        3
      ]
    }
  ],
  "goldens": [
    {
      "id": "case-0",
      "inputs": [
        "0/in/left.bin",
        "0/in/right.bin"
      ],
      "outputs": [
        "0/out/primary.bin",
        "0/out/auxiliary.bin"
      ]
    },
    {
      "id": "case-1",
      "inputs": [
        "1/in/left.bin",
        "1/in/right.bin"
      ],
      "outputs": [
        "1/out/primary.bin",
        "1/out/auxiliary.bin"
      ]
    },
    {
      "id": "case-2",
      "inputs": [
        "2/in/left.bin",
        "2/in/right.bin"
      ],
      "outputs": [
        "2/out/primary.bin",
        "2/out/auxiliary.bin"
      ]
    },
    {
      "id": "case-3",
      "inputs": [
        "3/in/left.bin",
        "3/in/right.bin"
      ],
      "outputs": [
        "3/out/primary.bin",
        "3/out/auxiliary.bin"
      ]
    }
  ]
}
''';

  static ModelManifest? _manifest;

  /// The contract, parsed once.
  static ModelManifest get manifest =>
      _manifest ??= ManifestCodec.decode(manifestJson);

  /// Digest of the artifact this class was generated for.
  static const String weightHash =
      'sha256:c5805f1ce29c3d33620d445ec42f8dfd47ab3f8956a647ec5823f5ede46bf9c7';

  /// Loads [artifact] on [runtime], refusing one that does not match
  /// [weightHash].
  ///
  /// The check is not optional: an artifact paired with the wrong
  /// contract satisfies every shape and returns every number wrong.
  static Future<MultiIo> load(
    FluttorchRuntime runtime, {
    required Uint8List artifact,
    String? backend,
  }) async {
    verifyArtifact(artifact: artifact, manifest: manifest);
    return MultiIo._(
      await runtime.load(
        artifact: artifact,
        manifest: manifest,
        backend: backend,
      ),
    );
  }

  /// Wraps a model loaded through some other path — an isolate,
  /// a cache, a pool — checking that it is this model.
  ///
  /// Throws [ArtifactMismatchException] if the loaded model was
  /// built from a different export.
  factory MultiIo.wrap(LoadedModel loaded) {
    if (loaded.manifest.weightHash != weightHash) {
      throw ArtifactMismatchException(
        expectedHash: weightHash,
        actualHash: loaded.manifest.weightHash,
      );
    }
    return MultiIo._(loaded);
  }

  /// Runs inference.
  ///
  /// The parameter types are what makes a wrong tensor a compile
  /// error; nothing here can be called with the arguments in the
  /// wrong order.
  Future<MultiIoOutputs> run({
    required MultiIoLeft left,
    required MultiIoRight right,
  }) async => MultiIoOutputs._(await model.run([left.tensor, right.tensor]));

  /// Releases the native resources behind the model.
  Future<void> dispose() => model.dispose();
}
