// GENERATED BY fluttorch_gen — do not edit.
//
// Source: two_layer.fluttorch.json
// Manifest schema 1
// Weights: sha256:0643556a16ee892399c1dcc2f344f33c3f92f889c458be771c913bda5ce13cb9
//
// Editing this file lets the Dart side disagree with the export it
// came from, which is the failure this generator exists to prevent.
// Change the model, re-export, and rebuild.

// ignore_for_file: unnecessary_cast, unused_import

import 'dart:typed_data';

import 'package:fluttorch/fluttorch.dart';

/// The `features` input: `float32[1, 4]`.
///
/// A distinct type rather than a bare [Tensor], so passing the wrong
/// tensor to [TwoLayer.run] is a compile error rather than a shape
/// mismatch discovered at inference. The wrapper costs nothing at
/// run time.
extension type const TwoLayerFeatures._(Tensor tensor) {
  /// What the export declared for this tensor.
  static const TensorSpec spec = TensorSpec(
    name: 'features',
    dtype: DType.float32,
    shape: [1, 4],
  );

  /// Wraps 4 `float32` values.
  ///
  /// Throws [TensorShapeException] unless [values] holds exactly
  /// 4; the shape itself is fixed by the export.
  factory TwoLayerFeatures(Float32List values) {
    if (values.length != 4) {
      throw TensorShapeException(
        'expected 4 values, got ${values.length}',
        tensorName: 'features',
      );
    }
    return TwoLayerFeatures._(
      Tensor.view(
        spec: spec,
        bytes: values.buffer.asUint8List(
          values.offsetInBytes,
          values.lengthInBytes,
        ),
      ),
    );
  }

  /// An all-zero tensor, for use as a destination buffer.
  factory TwoLayerFeatures.zeros() => TwoLayerFeatures._(Tensor.zeros(spec));

  /// Wraps a tensor that already satisfies [spec].
  ///
  /// Throws [TensorShapeException] or [DTypeMismatchException] if it
  /// does not.
  factory TwoLayerFeatures.wrap(Tensor tensor) {
    checkTensorsAgainst([spec], [tensor], role: 'features');
    return TwoLayerFeatures._(tensor);
  }

  /// The values, over the same memory. No copy is made.
  Float32List get values => tensor.asFloat32List();

  /// The concrete shape, which for a dynamic spec is known only here.
  List<int> get shape => tensor.shape;
}

/// The `score` output: `float32[1, 3]`.
///
/// A distinct type rather than a bare [Tensor], so passing the wrong
/// tensor to [TwoLayer.run] is a compile error rather than a shape
/// mismatch discovered at inference. The wrapper costs nothing at
/// run time.
extension type const TwoLayerScore._(Tensor tensor) {
  /// What the export declared for this tensor.
  static const TensorSpec spec = TensorSpec(
    name: 'score',
    dtype: DType.float32,
    shape: [1, 3],
  );

  /// Wraps 3 `float32` values.
  ///
  /// Throws [TensorShapeException] unless [values] holds exactly
  /// 3; the shape itself is fixed by the export.
  factory TwoLayerScore(Float32List values) {
    if (values.length != 3) {
      throw TensorShapeException(
        'expected 3 values, got ${values.length}',
        tensorName: 'score',
      );
    }
    return TwoLayerScore._(
      Tensor.view(
        spec: spec,
        bytes: values.buffer.asUint8List(
          values.offsetInBytes,
          values.lengthInBytes,
        ),
      ),
    );
  }

  /// An all-zero tensor, for use as a destination buffer.
  factory TwoLayerScore.zeros() => TwoLayerScore._(Tensor.zeros(spec));

  /// Wraps a tensor that already satisfies [spec].
  ///
  /// Throws [TensorShapeException] or [DTypeMismatchException] if it
  /// does not.
  factory TwoLayerScore.wrap(Tensor tensor) {
    checkTensorsAgainst([spec], [tensor], role: 'score');
    return TwoLayerScore._(tensor);
  }

  /// The values, over the same memory. No copy is made.
  Float32List get values => tensor.asFloat32List();

  /// The concrete shape, which for a dynamic spec is known only here.
  List<int> get shape => tensor.shape;
}

/// What [TwoLayer.run] returns.
final class TwoLayerOutputs {
  const TwoLayerOutputs._(this._tensors);

  final List<Tensor> _tensors;

  /// The `score` output.
  TwoLayerScore get score => TwoLayerScore._(_tensors[0]);

  /// The class labels the export recorded, in order.
  static const List<String> labels = ['low', 'mid', 'high'];

  /// Every output, positional with the manifest.
  List<Tensor> get tensors => List.unmodifiable(_tensors);
}

/// `two_layer`, as exported.
///
/// Carries its own manifest, so loading verifies the artifact against
/// the contract it was generated from without any separate plumbing.
final class TwoLayer {
  const TwoLayer._(this.model);

  /// The loaded model this wraps, for anything the generated API
  /// does not cover.
  final LoadedModel model;

  /// The manifest this class was generated from, embedded verbatim.
  static const String manifestJson = r'''
{
  "schema_version": 1,
  "name": "two_layer",
  "weight_hash": "sha256:0643556a16ee892399c1dcc2f344f33c3f92f889c458be771c913bda5ce13cb9",
  "inputs": [
    {
      "name": "features",
      "dtype": "float32",
      "shape": [
        1,
        4
      ]
    }
  ],
  "outputs": [
    {
      "name": "score",
      "dtype": "float32",
      "shape": [
        1,
        3
      ]
    }
  ],
  "labels": [
    "low",
    "mid",
    "high"
  ],
  "goldens": [
    {
      "id": "case-0",
      "inputs": [
        "0/in/features.bin"
      ],
      "outputs": [
        "0/out/score.bin"
      ]
    },
    {
      "id": "case-1",
      "inputs": [
        "1/in/features.bin"
      ],
      "outputs": [
        "1/out/score.bin"
      ]
    },
    {
      "id": "case-2",
      "inputs": [
        "2/in/features.bin"
      ],
      "outputs": [
        "2/out/score.bin"
      ]
    },
    {
      "id": "case-3",
      "inputs": [
        "3/in/features.bin"
      ],
      "outputs": [
        "3/out/score.bin"
      ]
    }
  ]
}
''';

  static ModelManifest? _manifest;

  /// The contract, parsed once.
  static ModelManifest get manifest =>
      _manifest ??= ManifestCodec.decode(manifestJson);

  /// Digest of the artifact this class was generated for.
  static const String weightHash =
      'sha256:0643556a16ee892399c1dcc2f344f33c3f92f889c458be771c913bda5ce13cb9';

  /// Loads [artifact] on [runtime], refusing one that does not match
  /// [weightHash].
  ///
  /// The check is not optional: an artifact paired with the wrong
  /// contract satisfies every shape and returns every number wrong.
  static Future<TwoLayer> load(
    FluttorchRuntime runtime, {
    required Uint8List artifact,
    String? backend,
  }) async {
    verifyArtifact(artifact: artifact, manifest: manifest);
    return TwoLayer._(
      await runtime.load(
        artifact: artifact,
        manifest: manifest,
        backend: backend,
      ),
    );
  }

  /// Wraps a model loaded through some other path — an isolate,
  /// a cache, a pool — checking that it is this model.
  ///
  /// Throws [ArtifactMismatchException] if the loaded model was
  /// built from a different export.
  factory TwoLayer.wrap(LoadedModel loaded) {
    if (loaded.manifest.weightHash != weightHash) {
      throw ArtifactMismatchException(
        expectedHash: weightHash,
        actualHash: loaded.manifest.weightHash,
      );
    }
    return TwoLayer._(loaded);
  }

  /// Runs inference.
  ///
  /// The parameter types are what makes a wrong tensor a compile
  /// error; nothing here can be called with the arguments in the
  /// wrong order.
  Future<TwoLayerOutputs> run({required TwoLayerFeatures features}) async =>
      TwoLayerOutputs._(await model.run([features.tensor]));

  /// Releases the native resources behind the model.
  Future<void> dispose() => model.dispose();
}
