// GENERATED BY fluttorch_gen — do not edit.
//
// Source: vision.fluttorch.json
// Manifest schema 1
// Weights: sha256:9720e97e03c49e25fb8e764af588ba5b7c1e0dbff638e2381846384b74235a53
//
// Editing this file lets the Dart side disagree with the export it
// came from, which is the failure this generator exists to prevent.
// Change the model, re-export, and rebuild.

// ignore_for_file: unnecessary_cast, unused_import

import 'dart:typed_data';

import 'package:fluttorch/fluttorch.dart';

/// The `image` input: `float32[1, 3, 8, 8]`.
///
/// A distinct type rather than a bare [Tensor], so passing the wrong
/// tensor to [Vision.run] is a compile error rather than a shape
/// mismatch discovered at inference. The wrapper costs nothing at
/// run time.
extension type const VisionImage._(Tensor tensor) {
  /// What the export declared for this tensor.
  static const TensorSpec spec = TensorSpec(
    name: 'image',
    dtype: DType.float32,
    shape: [1, 3, 8, 8],
    layout: TensorLayout.nchw,
  );

  /// Wraps 192 `float32` values.
  ///
  /// Throws [TensorShapeException] unless [values] holds exactly
  /// 192; the shape itself is fixed by the export.
  factory VisionImage(Float32List values) {
    if (values.length != 192) {
      throw TensorShapeException(
        'expected 192 values, got ${values.length}',
        tensorName: 'image',
      );
    }
    return VisionImage._(
      Tensor.view(
        spec: spec,
        bytes: values.buffer.asUint8List(
          values.offsetInBytes,
          values.lengthInBytes,
        ),
      ),
    );
  }

  /// An all-zero tensor, for use as a destination buffer.
  factory VisionImage.zeros() => VisionImage._(Tensor.zeros(spec));

  /// Builds this tensor from a source image of [height] by
  /// [width], applying the spatial steps the export recorded.
  ///
  /// Separate from [preprocess] because these steps change the
  /// number of elements, so they cannot run in place. The
  /// elementwise steps stay there, and the manifest is refused
  /// unless it records the spatial ones first, so calling this
  /// and then [preprocess] replays the recorded order exactly.
  ///
  /// Throws [TensorShapeException] unless [values] holds
  /// 1 × 3 × [height] × [width] elements.
  factory VisionImage.fromSource(
    Float32List values, {
    required int height,
    required int width,
  }) {
    const batch = 1;
    const channels = 3;
    final expected = batch * channels * height * width;
    if (values.length != expected) {
      throw TensorShapeException(
        'expected $expected values for a ${height}x$width source, '
        'got ${values.length}',
        tensorName: 'image',
      );
    }
    // nchw: the axis order the manifest declared.
    int at(int n, int c, int y, int x, int h, int w) =>
        ((n * channels + c) * h + y) * w + x;
    var src = values;
    var sh = height;
    var sw = width;
    // resize to 13 x 11, bilinear
    {
      const oh = 13;
      const ow = 11;
      final dst = Float32List(batch * channels * oh * ow);
      final ry = sh / oh;
      final rx = sw / ow;
      for (var n = 0; n < batch; n++) {
        for (var c = 0; c < channels; c++) {
          for (var y = 0; y < oh; y++) {
            for (var x = 0; x < ow; x++) {
              var fy = (y + 0.5) * ry - 0.5;
              if (fy < 0) fy = 0;
              var fx = (x + 0.5) * rx - 0.5;
              if (fx < 0) fx = 0;
              final y0 = fy.floor();
              final x0 = fx.floor();
              final y1 = y0 + 1 < sh ? y0 + 1 : sh - 1;
              final x1 = x0 + 1 < sw ? x0 + 1 : sw - 1;
              final wy = fy - y0;
              final wx = fx - x0;
              final p00 = src[at(n, c, y0, x0, sh, sw)];
              final p01 = src[at(n, c, y0, x1, sh, sw)];
              final p10 = src[at(n, c, y1, x0, sh, sw)];
              final p11 = src[at(n, c, y1, x1, sh, sw)];
              dst[at(n, c, y, x, oh, ow)] =
                  (1 - wy) * ((1 - wx) * p00 + wx * p01) +
                  wy * ((1 - wx) * p10 + wx * p11);
            }
          }
        }
      }
      src = dst;
      sh = oh;
      sw = ow;
    }
    // center_crop 8 x 8
    {
      const oh = 8;
      const ow = 8;
      if (sh < oh || sw < ow) {
        throw TensorShapeException(
          'cannot crop ${oh}x$ow out of ${sh}x$sw',
          tensorName: spec.name,
        );
      }
      int half(int margin) {
        final v = margin / 2;
        final f = v.floor();
        if (v - f != 0.5) return v.round();
        return f.isEven ? f : f + 1;
      }

      final top = half(sh - oh);
      final left = half(sw - ow);
      final dst = Float32List(batch * channels * oh * ow);
      for (var n = 0; n < batch; n++) {
        for (var c = 0; c < channels; c++) {
          for (var y = 0; y < oh; y++) {
            for (var x = 0; x < ow; x++) {
              dst[at(n, c, y, x, oh, ow)] =
                  src[at(n, c, top + y, left + x, sh, sw)];
            }
          }
        }
      }
      src = dst;
      sh = oh;
      sw = ow;
    }
    return VisionImage(src);
  }

  /// Wraps a tensor that already satisfies [spec].
  ///
  /// Throws [TensorShapeException] or [DTypeMismatchException] if it
  /// does not.
  factory VisionImage.wrap(Tensor tensor) {
    checkTensorsAgainst([spec], [tensor], role: 'image');
    return VisionImage._(tensor);
  }

  /// The values, over the same memory. No copy is made.
  Float32List get values => tensor.asFloat32List();

  /// The concrete shape, which for a dynamic spec is known only here.
  List<int> get shape => tensor.shape;
}

/// The transforms the export recorded for `image`.
///
/// Generated from the manifest, so they cannot drift from the ones
/// training applied — which is the whole reason they are not written
/// by hand.
extension VisionImagePreprocessing on VisionImage {
  /// Applies every recorded step, in order, in place.
  ///
  /// In place because the caller owns the buffer and a preprocessing
  /// pass that allocated would undo the point of owning it.
  void preprocess() {
    // normalize over axis 1, 3 channels
    {
      const mean = [0.485, 0.456, 0.406];
      const std = [0.229, 0.224, 0.225];
      final v = values;
      for (var i = 0; i < v.length; i++) {
        final c = (i ~/ 64) % 3;
        v[i] = (v[i] - mean[c]) / std[c];
      }
    }
  }
}

/// The `logits` output: `float32[1, 2]`.
///
/// A distinct type rather than a bare [Tensor], so passing the wrong
/// tensor to [Vision.run] is a compile error rather than a shape
/// mismatch discovered at inference. The wrapper costs nothing at
/// run time.
extension type const VisionLogits._(Tensor tensor) {
  /// What the export declared for this tensor.
  static const TensorSpec spec = TensorSpec(
    name: 'logits',
    dtype: DType.float32,
    shape: [1, 2],
  );

  /// Wraps 2 `float32` values.
  ///
  /// Throws [TensorShapeException] unless [values] holds exactly
  /// 2; the shape itself is fixed by the export.
  factory VisionLogits(Float32List values) {
    if (values.length != 2) {
      throw TensorShapeException(
        'expected 2 values, got ${values.length}',
        tensorName: 'logits',
      );
    }
    return VisionLogits._(
      Tensor.view(
        spec: spec,
        bytes: values.buffer.asUint8List(
          values.offsetInBytes,
          values.lengthInBytes,
        ),
      ),
    );
  }

  /// An all-zero tensor, for use as a destination buffer.
  factory VisionLogits.zeros() => VisionLogits._(Tensor.zeros(spec));

  /// Wraps a tensor that already satisfies [spec].
  ///
  /// Throws [TensorShapeException] or [DTypeMismatchException] if it
  /// does not.
  factory VisionLogits.wrap(Tensor tensor) {
    checkTensorsAgainst([spec], [tensor], role: 'logits');
    return VisionLogits._(tensor);
  }

  /// The values, over the same memory. No copy is made.
  Float32List get values => tensor.asFloat32List();

  /// The concrete shape, which for a dynamic spec is known only here.
  List<int> get shape => tensor.shape;
}

/// What [Vision.run] returns.
final class VisionOutputs {
  const VisionOutputs._(this._tensors);

  final List<Tensor> _tensors;

  /// The `logits` output.
  VisionLogits get logits => VisionLogits._(_tensors[0]);

  /// Every output, positional with the manifest.
  List<Tensor> get tensors => List.unmodifiable(_tensors);
}

/// `vision`, as exported.
///
/// Carries its own manifest, so loading verifies the artifact against
/// the contract it was generated from without any separate plumbing.
final class Vision {
  const Vision._(this.model);

  /// The loaded model this wraps, for anything the generated API
  /// does not cover.
  final LoadedModel model;

  /// The manifest this class was generated from, embedded verbatim.
  static const String manifestJson = r'''
{
  "schema_version": 1,
  "name": "vision",
  "weight_hash": "sha256:9720e97e03c49e25fb8e764af588ba5b7c1e0dbff638e2381846384b74235a53",
  "inputs": [
    {
      "name": "image",
      "dtype": "float32",
      "shape": [
        1,
        3,
        8,
        8
      ],
      "layout": "nchw"
    }
  ],
  "outputs": [
    {
      "name": "logits",
      "dtype": "float32",
      "shape": [
        1,
        2
      ]
    }
  ],
  "preprocessing": [
    {
      "kind": "resize",
      "height": 13,
      "width": 11,
      "interpolation": "bilinear"
    },
    {
      "kind": "center_crop",
      "height": 8,
      "width": 8
    },
    {
      "kind": "normalize",
      "mean": [
        0.485,
        0.456,
        0.406
      ],
      "std": [
        0.229,
        0.224,
        0.225
      ],
      "axis": 1
    }
  ],
  "goldens": [
    {
      "id": "case-0",
      "inputs": [
        "0/in/image.bin"
      ],
      "outputs": [
        "0/out/logits.bin"
      ]
    },
    {
      "id": "case-1",
      "inputs": [
        "1/in/image.bin"
      ],
      "outputs": [
        "1/out/logits.bin"
      ]
    },
    {
      "id": "case-2",
      "inputs": [
        "2/in/image.bin"
      ],
      "outputs": [
        "2/out/logits.bin"
      ]
    }
  ]
}
''';

  static ModelManifest? _manifest;

  /// The contract, parsed once.
  static ModelManifest get manifest =>
      _manifest ??= ManifestCodec.decode(manifestJson);

  /// Digest of the artifact this class was generated for.
  static const String weightHash =
      'sha256:9720e97e03c49e25fb8e764af588ba5b7c1e0dbff638e2381846384b74235a53';

  /// Loads [artifact] on [runtime], refusing one that does not match
  /// [weightHash].
  ///
  /// The check is not optional: an artifact paired with the wrong
  /// contract satisfies every shape and returns every number wrong.
  static Future<Vision> load(
    FluttorchRuntime runtime, {
    required Uint8List artifact,
    String? backend,
  }) async {
    verifyArtifact(artifact: artifact, manifest: manifest);
    return Vision._(
      await runtime.load(
        artifact: artifact,
        manifest: manifest,
        backend: backend,
      ),
    );
  }

  /// Wraps a model loaded through some other path — an isolate,
  /// a cache, a pool — checking that it is this model.
  ///
  /// Throws [ArtifactMismatchException] if the loaded model was
  /// built from a different export.
  factory Vision.wrap(LoadedModel loaded) {
    if (loaded.manifest.weightHash != weightHash) {
      throw ArtifactMismatchException(
        expectedHash: weightHash,
        actualHash: loaded.manifest.weightHash,
      );
    }
    return Vision._(loaded);
  }

  /// Runs inference.
  ///
  /// The parameter types are what makes a wrong tensor a compile
  /// error; nothing here can be called with the arguments in the
  /// wrong order.
  Future<VisionOutputs> run({required VisionImage image}) async =>
      VisionOutputs._(await model.run([image.tensor]));

  /// Releases the native resources behind the model.
  Future<void> dispose() => model.dispose();
}
